### ISSUE TITLE
Bug in validator?

### ISSUE THREAD

**Issue by magdalenafuentes** [mir-dataset-loaders/mirdata#57]
When I'm loading **any** dataset like this:
```
from mirdata import orchset
orchset.download()
orchset.load()
```
I get the following error:
```Traceback (most recent call last):
  File "/home/mfuentes/astre/code/repositories/mirdata/tests/tmp.py", line 10, in <module>
    orchset.load()
  File "/home/mfuentes/astre/code/repositories/mirdata/mirdata/orchset.py", line 79, in load
    validate(data_home)
  File "/home/mfuentes/astre/code/repositories/mirdata/mirdata/orchset.py", line 70, in validate
    missing_files, invalid_checksums = utils.validator(ORCHSET_INDEX, data_home, dataset_path)
  File "/home/mfuentes/astre/code/repositories/mirdata/mirdata/utils.py", line 75, in validator
    if check_validated(dataset_path):
  File "/home/mfuentes/astre/code/repositories/mirdata/mirdata/utils.py", line 293, in check_validated
    return os.path.exists(os.path.join(dataset_path, VALIDATED_FILE_NAME))
  File "/home/mfuentes/anaconda3/envs/struct/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I think checking `dataset_path is None` or similar might be missing in the validator.

**Comment by magdalenafuentes** [comment]
Fixed in #58
