### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by hyve9** [mir-dataset-loaders/mirdata#627]
It looks like mirdata still depends on imp, which was deprecated in 3.11 and removed in 3.12:

```
pip install mirdata 
Collecting mirdata
  Using cached mirdata-0.3.8-py3-none-any.whl.metadata (6.6 kB)
Collecting attrs>=23.1.0 (from mirdata)
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Collecting black>=23.3.0 (from mirdata)
  Using cached black-24.3.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (75 kB)
Collecting chardet>=5.0.0 (from mirdata)
  Using cached chardet-5.2.0-py3-none-any.whl.metadata (3.4 kB)
Collecting Deprecated>=1.2.14 (from mirdata)
  Using cached Deprecated-1.2.14-py2.py3-none-any.whl.metadata (5.4 kB)
Collecting jams>=0.3.4 (from mirdata)
  Using cached jams-0.3.4.tar.gz (51 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-gavk7r0k/jams_b471981ad2754869a2455feefe6ac42e/setup.py", line 3, in <module>
          import imp
      ModuleNotFoundError: No module named 'imp'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

Recommend to replace imp with importlib: https://docs.python.org/3/library/importlib.html#module-importlib

**Comment by hyve9** [comment]
Actually, it's not mirdata - mirdata already supports 3.12. It's Jams (https://github.com/marl/jams). This PR should resolve:
https://github.com/marl/jams/pull/215

**Comment by madderscientist** [comment]
> Actually, it's not mirdata - mirdata already supports 3.12. It's Jams (https://github.com/marl/jams). This PR should resolve: [marl/jams#215](https://github.com/marl/jams/pull/215)

Thank you for this message, which helps me successfully installed mirdata in python312! I‘m writing the installation steps here to assist those who come later.

As jams hasn't update its pip source since 2019, we should install from source code, which could be downloaded from [jams](https://github.com/marl/jams). In its root directory run "python setup.py install", then just "pip install mirdata"!

**Comment by Masetto96** [comment]
Thank you for your patience. We are currently working on adding support for Python 3.12.

**Comment by Laubeee** [comment]
@Masetto96 any plans for releasing this?
